---
abstract: 'find the nearest module to a given name.'
author:
  - 'Ben Bullock <bkb@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Nearest
no_index:
  directory:
    - t
    - inc
requires:
  Text::Fuzzy: 0.11
resources:
  bugtracker: https://github.com/benkasminbullock/nearest-module/issues
  repository: https://github.com/benkasminbullock/nearest-module
version: 0.09_02
